### ISSUE TITLE
评论区会有一些不能直接播放的媒体文件不会自动下载

### ISSUE THREAD

**Issue by zhx119911** [Gentlesprite/Telegram-Restricted-Media-Downloader#4]
如题，有一些“文件”类型的MP4 MKV不会自动下载，会漏掉

**Comment by Gentlesprite** [comment]
确实存在该问题，会修复。

**Comment by Gentlesprite** [comment]
代码确实没有考虑到"文件"类型的媒体文件，已在最新的v1.2.2中修复，下载并更新至v1.2.2即可解决。
https://github.com/Gentlesprite/Telegram-Restricted-Media-Downloader/releases/tag/v1.2.2
